# Generated by Django 5.2.6 on 2025-09-28 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("containers", "0002_alter_container_direct_service"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=15)),
                ("ppu", models.CharField(max_length=10, verbose_name="PPU")),
                ("tracto", models.CharField(blank=True, max_length=10)),
                (
                    "tipo_conductor",
                    models.CharField(
                        choices=[
                            ("LEASING", "Leasing"),
                            ("LOCALERO", "Localero"),
                            ("TRONCO_PM", "Tronco PM"),
                            ("TRONCO", "Tronco"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("OPERATIVO", "Operativo"),
                            ("PANNE", "Panne"),
                            ("PERMISO", "Permiso"),
                            ("NO_DISPONIBLE", "No Disponible"),
                            ("AUSENTE", "Ausente"),
                        ],
                        default="OPERATIVO",
                        max_length=20,
                    ),
                ),
                ("coordinador", models.CharField(blank=True, max_length=50)),
                ("faena", models.CharField(blank=True, max_length=50)),
                (
                    "ubicacion_actual",
                    models.CharField(
                        choices=[
                            ("CCTI", "CCTI - Base Maipú"),
                            ("CD_QUILICURA", "CD Quilicura"),
                            ("CD_CAMPOS", "CD Campos de Chile - Pudahuel"),
                            ("CD_MADERO", "CD Puerto Madero - Pudahuel"),
                            ("CD_PENON", "CD El Peñón - San Bernardo"),
                            ("PUERTO_VALPARAISO", "Puerto Valparaíso"),
                            ("PUERTO_SAN_ANTONIO", "Puerto San Antonio"),
                            ("EN_RUTA", "En Ruta"),
                            ("ALMACEN_EXTRAPORTUARIO", "Almacén Extraportuario"),
                        ],
                        default="CCTI",
                        max_length=50,
                    ),
                ),
                ("tiempo_en_ubicacion", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "ingresa_agy",
                    models.BooleanField(default=True, verbose_name="Ingresa AGY"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contenedor_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conductor_asignado",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conductor",
                "verbose_name_plural": "Conductores",
                "db_table": "drivers",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_programada", models.DateTimeField()),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_CURSO", "En Curso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("origen", models.CharField(max_length=100)),
                ("destino", models.CharField(max_length=100)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="containers.container",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drivers.driver"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación",
                "verbose_name_plural": "Asignaciones",
                "db_table": "assignments",
                "ordering": ["-fecha_asignacion"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONTENEDOR_SIN_ASIGNAR", "Contenedor sin asignar"),
                            ("DEMURRAGE_PROXIMO", "Demurrage próximo"),
                            ("CONDUCTOR_INACTIVO", "Conductor inactivo"),
                            ("RETRASO_PROGRAMACION", "Retraso en programación"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="containers.container",
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "db_table": "alerts",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
