# Generated by Django 5.2.6 on 2025-09-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = []
