# Generated by Django 5.2.6 on 2025-09-28 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_auto_20250928_1723"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("address", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "drivers_location",
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="destino_legacy",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="assignment",
            name="origen_legacy",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="assignment",
            name="tiempo_estimado",
            field=models.IntegerField(
                default=120, help_text="Tiempo estimado en minutos"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="tiempo_real",
            field=models.IntegerField(
                blank=True, help_text="Tiempo real en minutos", null=True
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="destino",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments_to",
                to="drivers.location",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="origen",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments_from",
                to="drivers.location",
            ),
        ),
        migrations.CreateModel(
            name="TimeMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "travel_time",
                    models.IntegerField(help_text="Tiempo de viaje en minutos"),
                ),
                (
                    "loading_time",
                    models.IntegerField(
                        default=0, help_text="Tiempo de carga en minutos"
                    ),
                ),
                (
                    "unloading_time",
                    models.IntegerField(
                        default=0, help_text="Tiempo de descarga en minutos"
                    ),
                ),
                (
                    "avg_travel_time",
                    models.FloatField(
                        blank=True, help_text="Tiempo promedio histórico", null=True
                    ),
                ),
                ("min_travel_time", models.IntegerField(blank=True, null=True)),
                ("max_travel_time", models.IntegerField(blank=True, null=True)),
                ("total_trips", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_from",
                        to="drivers.location",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_to",
                        to="drivers.location",
                    ),
                ),
            ],
            options={
                "db_table": "drivers_time_matrix",
                "unique_together": {("from_location", "to_location")},
            },
        ),
    ]
