# Generated by Django 5.2.6 on 2025-09-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "containers",
            "0004_alter_container_options_container_conductor_asignado_and_more",
        ),
        ("drivers", "0003_location_assignment_destino_legacy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="hora_ingreso_hoy",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Hora de ingreso hoy"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="ultimo_registro_asistencia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Último registro"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="contenedor_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_assigned",
                to="containers.container",
            ),
        ),
    ]
