# Generated by Django 5.2.6 on 2025-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_driver_hora_ingreso_hoy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="tipo_asignacion",
            field=models.CharField(
                choices=[
                    ("ENTREGA", "Entrega a cliente"),
                    ("DEVOLUCION", "Devolución a depósito/CCTI"),
                ],
                default="ENTREGA",
                max_length=20,
                verbose_name="Tipo de asignación",
            ),
        ),
    ]
