# Generated by Django 5.2.6 on 2025-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0005_enhance_return_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="descarga_minutos_real",
            field=models.IntegerField(
                blank=True, help_text="Tiempo real de descarga", null=True
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="ruta_minutos_real",
            field=models.IntegerField(
                blank=True, help_text="Tiempo real de ruta", null=True
            ),
        ),
    ]
