# Generated by Django 5.2.6 on 2025-10-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0006_add_assignment_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_name", models.CharField(help_text="Origen", max_length=200)),
                (
                    "destination_name",
                    models.CharField(help_text="Destino", max_length=200),
                ),
                (
                    "traffic_level",
                    models.CharField(
                        choices=[
                            ("low", "Tráfico Bajo"),
                            ("medium", "Tráfico Medio"),
                            ("high", "Tráfico Alto"),
                            ("very_high", "Tráfico Muy Alto"),
                        ],
                        help_text="Nivel de tráfico",
                        max_length=20,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("TRAFFIC", "Tráfico Denso"),
                            ("ACCIDENT", "Accidente"),
                            ("ROAD_CLOSURE", "Carretera Cerrada"),
                            ("CONSTRUCTION", "Obras en Ruta"),
                            ("DELAY", "Retraso Estimado"),
                            ("ALTERNATIVE", "Ruta Alternativa Disponible"),
                        ],
                        help_text="Tipo de alerta",
                        max_length=30,
                    ),
                ),
                (
                    "estimated_time_minutes",
                    models.IntegerField(
                        help_text="Tiempo estimado sin tráfico (minutos)"
                    ),
                ),
                (
                    "actual_time_minutes",
                    models.IntegerField(
                        help_text="Tiempo actual con tráfico (minutos)"
                    ),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(
                        help_text="Retraso adicional por tráfico (minutos)"
                    ),
                ),
                ("departure_time", models.DateTimeField(help_text="Hora de salida")),
                (
                    "estimated_arrival",
                    models.DateTimeField(help_text="Hora estimada de llegada (ETA)"),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Mensaje de la alerta para el conductor"
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Advertencias específicas (JSON array)",
                    ),
                ),
                (
                    "has_alternatives",
                    models.BooleanField(
                        default=False, help_text="¿Hay rutas alternativas disponibles?"
                    ),
                ),
                (
                    "alternative_routes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Rutas alternativas sugeridas (JSON array)",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos completos de Google Maps API",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="¿Alerta activa?"),
                ),
                (
                    "acknowledged",
                    models.BooleanField(
                        default=False, help_text="¿Conductor confirmó recepción?"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de confirmación", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Asignación asociada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_alerts",
                        to="drivers.assignment",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Conductor notificado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_alerts",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Tráfico",
                "verbose_name_plural": "Alertas de Tráfico",
                "db_table": "drivers_traffic_alert",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["driver", "-created_at"],
                        name="drivers_tra_driver__76e9e8_idx",
                    ),
                    models.Index(
                        fields=["assignment", "-created_at"],
                        name="drivers_tra_assignm_7a4c52_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="drivers_tra_is_acti_3f228f_idx",
                    ),
                ],
            },
        ),
    ]
