# Generated by Django 5.2.6 on 2025-10-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0007_trafficalert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficalert",
            name="raw_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Datos completos devueltos por Mapbox API",
            ),
        ),
    ]
