# Generated by Django 5.2.6 on 2025-10-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0008_alter_trafficalert_raw_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Ciudad"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(
                default="Chile", max_length=100, verbose_name="País"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Región"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.TextField(blank=True, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=10,
                null=True,
                verbose_name="Latitud",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name="Longitud",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nombre"),
        ),
    ]
