# Generated by Django 5.2.6 on 2025-10-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0009_extend_location_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CONTENEDOR_SIN_ASIGNAR", "Contenedor sin asignar"),
                    ("DEMURRAGE_PROXIMO", "Demurrage próximo"),
                    ("DEMURRAGE_VENCIDO", "Demurrage vencido"),
                    ("ENTREGA_RETRASADA", "Entrega retrasada"),
                    ("ASIGNACION_PENDIENTE", "Asignación sin iniciar"),
                    ("CONDUCTOR_INACTIVO", "Conductor inactivo"),
                    ("RETRASO_PROGRAMACION", "Retraso en programación"),
                ],
                max_length=30,
            ),
        ),
    ]
