# Generated by Django 5.2.6 on 2025-10-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0010_add_new_alert_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.CharField(
                default="", max_length=32, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="location",
            table="core_location",
        ),
    ]
