# Generated by Django 5.2.6 on 2025-10-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0011_add_traffic_info_to_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="mapbox_data",
            field=models.JSONField(
                blank=True,
                help_text="Datos completos de Mapbox API (rutas alternativas, warnings, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="traffic_level_at_assignment",
            field=models.CharField(
                choices=[
                    ("low", "Tráfico Bajo"),
                    ("medium", "Tráfico Medio"),
                    ("high", "Tráfico Alto"),
                    ("very_high", "Tráfico Muy Alto"),
                    ("unknown", "Desconocido"),
                ],
                default="unknown",
                help_text="Nivel de tráfico al momento de crear la asignación (desde Mapbox)",
                max_length=20,
            ),
        ),
    ]
