# Generated by Django 5.2.6 on 2025-10-09 22:26

import apps.drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0013_fix_location_table"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="location",
                    name="id",
                    field=models.CharField(
                        default=apps.drivers.models.generate_location_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterModelTable(
                    name="location",
                    table="core_location",
                ),
            ],
        ),
    ]
