# Generated by Django 5.1.4 on 2025-10-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0017_add_critical_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assignment",
            name="assignment_driver_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="assignment",
            name="assignment_container_estado_idx",
        ),
        migrations.RemoveIndex(
            model_name="assignment",
            name="assignment_estado_fecha_idx",
        ),
        migrations.RemoveIndex(
            model_name="driver",
            name="driver_rut_idx",
        ),
        migrations.RemoveIndex(
            model_name="driver",
            name="driver_estado_idx",
        ),
        migrations.RemoveIndex(
            model_name="driver",
            name="driver_ubicacion_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="location_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="location_code_idx",
        ),
    ]
