# Generated by Django 5.1.4 on 2025-10-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0018_remove_assignment_assignment_driver_date_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "managed": True,
                "ordering": ["name"],
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
            },
        ),
    ]
