# Generated by Django 5.2.6 on 2025-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="direct_service",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Servicio directo"
            ),
        ),
    ]
