# Generated by Django 5.2.6 on 2025-09-28 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0002_alter_container_direct_service"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="current_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EN_PISO", "En Piso"),
                    ("EN_CHASIS", "En Chasis"),
                    ("CCTI", "CCTI"),
                    ("ZEAL", "ZEAL"),
                    ("CLEP", "CLEP"),
                    ("EN_RUTA", "En Ruta"),
                    ("CD_QUILICURA", "CD Quilicura"),
                    ("CD_CAMPOS", "CD Campos"),
                    ("CD_MADERO", "CD Puerto Madero"),
                    ("CD_PENON", "CD El Peñón"),
                    ("DEPOSITO_DEVOLUCION", "Depósito Devolución"),
                ],
                max_length=30,
                verbose_name="Posición Actual",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="position_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="position_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="container_position_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("DIRECTO", "Directo"),
                    ("INDIRECTO_DEPOSITO", "Indirecto con Depósito"),
                    ("INDIRECTO_CD", "Indirecto CD"),
                    ("TRANSFERENCIA", "Transferencia"),
                ],
                max_length=30,
                verbose_name="Tipo de servicio",
            ),
        ),
    ]
