# Generated by Django 5.2.6 on 2025-09-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0003_container_current_position_and_more"),
        ("drivers", "0003_location_assignment_destino_legacy_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="container",
            options={
                "ordering": ["sequence_id", "container_number"],
                "verbose_name": "Contenedor",
                "verbose_name_plural": "Contenedores",
            },
        ),
        migrations.AddField(
            model_name="container",
            name="conductor_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contenedores_asignados",
                to="drivers.driver",
                verbose_name="Conductor asignado",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponible"),
                    ("in_transit", "En Tránsito"),
                    ("loading", "Cargando"),
                    ("unloading", "Descargando"),
                    ("maintenance", "Mantenimiento"),
                    ("damaged", "Dañado"),
                    ("out_of_service", "Fuera de Servicio"),
                    ("POR_ARRIBAR", "Por Arribar"),
                    ("EN_SECUENCIA", "En Secuencia"),
                    ("DESCARGADO", "Descargado"),
                    ("LIBERADO", "Liberado"),
                    ("PROGRAMADO", "Programado"),
                    ("ASIGNADO", "Asignado"),
                    ("EN_RUTA", "En Ruta"),
                    ("ARRIBADO", "Arribado"),
                    ("FINALIZADO", "Finalizado"),
                    ("TRG", "TRG"),
                    ("SECUENCIADO", "Secuenciado"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
