# Generated by Django 5.2.6 on 2025-09-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "containers",
            "0004_alter_container_options_container_conductor_asignado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="duracion_descarga",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duración descarga (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="duracion_ruta",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duración ruta (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="duracion_total",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duración total (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tiempo_asignacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tiempo de asignación"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tiempo_descarga",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tiempo de descarga"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tiempo_finalizacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tiempo finalización"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tiempo_inicio_ruta",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tiempo inicio ruta"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tiempo_llegada",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tiempo de llegada"
            ),
        ),
    ]
