# Generated by Django 5.2.6 on 2025-10-03 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0005_add_timing_fields"),
        ("core", "0001_initial"),
        ("drivers", "0004_driver_hora_ingreso_hoy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="container",
            index=models.Index(fields=["status"], name="idx_status"),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(fields=["scheduled_date"], name="idx_scheduled"),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(fields=["conductor_asignado"], name="idx_driver"),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(fields=["container_number"], name="idx_number"),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["status", "scheduled_date"], name="idx_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["conductor_asignado", "status"], name="idx_driver_status"
            ),
        ),
    ]
