# Generated by Django 5.2.6 on 2025-10-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0006_container_idx_status_container_idx_scheduled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponible"),
                    ("in_transit", "En Tránsito"),
                    ("loading", "Cargando"),
                    ("unloading", "Descargando"),
                    ("maintenance", "Mantenimiento"),
                    ("damaged", "Dañado"),
                    ("out_of_service", "Fuera de Servicio"),
                    ("POR_ARRIBAR", "Por Arribar"),
                    ("EN_SECUENCIA", "En Secuencia"),
                    ("DESCARGADO", "Descargado"),
                    ("LIBERADO", "Liberado"),
                    ("PROGRAMADO", "Programado"),
                    ("ASIGNADO", "Asignado"),
                    ("EN_RUTA", "En Ruta"),
                    ("ARRIBADO", "Arribado"),
                    ("DESCARGADO_CD", "Descargado en CD"),
                    ("DISPONIBLE_DEVOLUCION", "Disponible Devolución"),
                    ("EN_RUTA_DEVOLUCION", "En Ruta Devolución"),
                    ("FINALIZADO", "Finalizado"),
                    ("TRG", "TRG"),
                    ("SECUENCIADO", "Secuenciado"),
                ],
                default="available",
                max_length=30,
            ),
        ),
    ]
