# Generated by Django 5.2.6 on 2025-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0007_add_return_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="duracion_devolucion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duración devolución (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tiempo_arribo_devolucion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Arribo devolución"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tiempo_inicio_devolucion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Inicio devolución"
            ),
        ),
    ]
