# Generated by Django 5.2.6 on 2025-10-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0008_enhance_return_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="port",
            field=models.CharField(blank=True, max_length=50, verbose_name="Puerto"),
        ),
    ]
