# Generated by Django 5.2.6 on 2025-10-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0009_increase_port_max_length"),
        ("drivers", "0014_alter_location_id_alter_location_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="current_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_containers",
                to="drivers.location",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terminal_containers",
                to="drivers.location",
                verbose_name="Terminal",
            ),
        ),
        migrations.AlterField(
            model_name="containermovement",
            name="from_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="container_movements_from",
                to="drivers.location",
            ),
        ),
        migrations.AlterField(
            model_name="containermovement",
            name="to_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="container_movements_to",
                to="drivers.location",
            ),
        ),
    ]
