# Generated by Django 5.2.6 on 2025-10-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0002_refactor_container_models"),
        ("containers", "0010_alter_container_current_location_and_more"),
    ]

    operations = []
