# Generated by Django 5.1.4 on 2025-10-10 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0012_add_critical_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="container",
            name="container_number_idx",
        ),
        migrations.RemoveIndex(
            model_name="container",
            name="container_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="container",
            name="container_owner_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="container",
            name="container_location_idx",
        ),
        migrations.RemoveIndex(
            model_name="container",
            name="container_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="containerinspection",
            name="inspection_container_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="containermovement",
            name="movement_container_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="containermovement",
            name="movement_locations_idx",
        ),
        migrations.RemoveField(
            model_name="containerimportinfo",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="containerschedule",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="containerspec",
            name="is_active",
        ),
        migrations.AddField(
            model_name="containerimportinfo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containerimportinfo_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="containerimportinfo",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containerimportinfo_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="containerschedule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containerschedule_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="containerschedule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containerschedule_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="containerspec",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containerspec_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="containerspec",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containerspec_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="containerimportinfo",
            name="container",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_info",
                to="containers.container",
                verbose_name="Contenedor",
            ),
        ),
        migrations.AlterField(
            model_name="containerimportinfo",
            name="eta",
            field=models.DateField(
                blank=True, null=True, verbose_name="ETA (Estimated Time of Arrival)"
            ),
        ),
        migrations.AlterField(
            model_name="containerimportinfo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="containerschedule",
            name="container",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="containers.container",
                verbose_name="Contenedor",
            ),
        ),
        migrations.AlterField(
            model_name="containerschedule",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="containerspec",
            name="container",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spec",
                to="containers.container",
                verbose_name="Contenedor",
            ),
        ),
        migrations.AlterField(
            model_name="containerspec",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="containerspec",
            name="seal_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Número de sello"
            ),
        ),
        migrations.AlterField(
            model_name="containerspec",
            name="special_requirements",
            field=models.TextField(
                blank=True, verbose_name="Requerimientos especiales"
            ),
        ),
    ]
