# Generated by Django 5.2.6 on 2025-09-28 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("containers", "0002_alter_container_direct_service"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "warehouse_type",
                    models.CharField(
                        choices=[
                            ("container_yard", "Patio de Contenedores"),
                            ("covered", "Cubierto"),
                            ("open_air", "Aire Libre"),
                            ("refrigerated", "Refrigerado"),
                            ("hazardous", "Materiales Peligrosos"),
                            ("customs", "Zona Aduanera"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "total_capacity",
                    models.IntegerField(help_text="Capacidad total en TEU"),
                ),
                (
                    "current_occupancy",
                    models.IntegerField(default=0, help_text="Ocupación actual en TEU"),
                ),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_height_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("has_crane", models.BooleanField(default=False)),
                ("has_power", models.BooleanField(default=True)),
                ("has_security", models.BooleanField(default=True)),
                ("operating_hours_start", models.TimeField()),
                ("operating_hours_end", models.TimeField()),
                ("operates_weekends", models.BooleanField(default=False)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.location"
                    ),
                ),
                (
                    "manager_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_warehouses",
                        to="core.company",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Almacén",
                "verbose_name_plural": "Almacenes",
            },
        ),
        migrations.CreateModel(
            name="WarehouseZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("zone_code", models.CharField(max_length=20)),
                ("zone_name", models.CharField(max_length=100)),
                ("zone_type", models.CharField(blank=True, max_length=50)),
                ("capacity", models.IntegerField(help_text="Capacidad en TEU")),
                ("current_occupancy", models.IntegerField(default=0)),
                ("is_refrigerated", models.BooleanField(default=False)),
                ("is_covered", models.BooleanField(default=True)),
                ("is_hazardous_allowed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zona de Almacén",
                "verbose_name_plural": "Zonas de Almacén",
                "unique_together": {("warehouse", "zone_code")},
            },
        ),
        migrations.CreateModel(
            name="WarehouseReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reservation_code", models.CharField(max_length=50, unique=True)),
                ("container_count", models.IntegerField()),
                (
                    "container_types",
                    models.JSONField(
                        default=list, help_text="Tipos de contenedores a reservar"
                    ),
                ),
                ("reservation_date", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("active", "Activa"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("special_requirements", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "client_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="warehouses.warehouse",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouses.warehousezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de Almacén",
                "verbose_name_plural": "Reservas de Almacén",
                "ordering": ["-reservation_date"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("entry", "Ingreso"),
                            ("exit", "Salida"),
                            ("relocation", "Reubicación"),
                            ("inspection", "Inspección"),
                            ("maintenance", "Mantenimiento"),
                            ("inventory", "Inventario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operation_date", models.DateTimeField()),
                ("operator_name", models.CharField(max_length=200)),
                ("equipment_used", models.CharField(blank=True, max_length=200)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("issues_found", models.TextField(blank=True)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_operations",
                        to="containers.container",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="warehouses.warehouse",
                    ),
                ),
                (
                    "from_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_from",
                        to="warehouses.warehousezone",
                    ),
                ),
                (
                    "to_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_to",
                        to="warehouses.warehousezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operación de Almacén",
                "verbose_name_plural": "Operaciones de Almacén",
                "ordering": ["-operation_date"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("row", models.CharField(blank=True, max_length=10)),
                ("column", models.CharField(blank=True, max_length=10)),
                (
                    "stack_position",
                    models.IntegerField(
                        default=1, help_text="Posición en la pila (1 = abajo)"
                    ),
                ),
                ("entry_date", models.DateTimeField()),
                ("expected_exit_date", models.DateTimeField(blank=True, null=True)),
                ("actual_exit_date", models.DateTimeField(blank=True, null=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocked_reason", models.TextField(blank=True)),
                ("special_handling", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "container",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="containers.container",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="warehouses.warehouse",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouses.warehousezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock de Almacén",
                "verbose_name_plural": "Stock de Almacenes",
                "unique_together": {("warehouse", "container")},
            },
        ),
    ]
