# Generated by Django 5.2.6 on 2025-10-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0014_alter_location_id_alter_location_table"),
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="drivers.location"
            ),
        ),
    ]
