# Generated by Django 5.1.4 on 2025-10-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("containers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("import_embarque", "Importación Embarque"),
                            ("import_liberacion", "Importación Liberación"),
                            ("import_programacion", "Importación Programación"),
                            ("asignacion_driver", "Asignación de Conductor"),
                            ("inicio_ruta", "Inicio de Ruta"),
                            ("llegada_destino", "Llegada a Destino"),
                            ("devolucion_vacio", "Devolución Vacío"),
                            ("alerta_48h", "Alerta 48 Horas"),
                            ("cambio_estado", "Cambio de Estado"),
                            ("actualizacion_posicion", "Actualización de Posición"),
                            ("exportacion_stock", "Exportación de Stock"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "detalles",
                    models.JSONField(blank=True, default=dict, verbose_name="Detalles"),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Usuario"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Fecha"
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="containers.container",
                        verbose_name="Contenedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="events_even_event_t_e518f4_idx",
                    ),
                    models.Index(
                        fields=["container", "created_at"],
                        name="events_even_contain_8a8abc_idx",
                    ),
                ],
            },
        ),
    ]
