#!/usr/bin/env bash
# Script de diagnóstico para problemas de login en Render

echo "============================================================"
echo "🔍 DIAGNÓSTICO DE PROBLEMAS DE LOGIN EN RENDER"
echo "============================================================"
echo ""

echo "📋 POSIBLES CAUSAS DEL PROBLEMA:"
echo ""

echo "1️⃣  El superusuario NO se creó en el post-deploy"
echo "   - Verificar logs de Render en la sección 'Deploy Logs'"
echo "   - Buscar: '✅ Superusuario creado: admin'"
echo "   - Si dice 'ℹ️ Superusuario ya existe' está OK"
echo ""

echo "2️⃣  La base de datos de Render es DIFERENTE a la local"
echo "   - Render usa PostgreSQL (no SQLite)"
echo "   - Los datos locales NO están en Render"
echo "   - Necesitas que el post_deploy.sh se ejecute correctamente"
echo ""

echo "3️⃣  El post_deploy.sh NO se ejecutó"
echo "   - Verificar en render.yaml si está configurado"
echo "   - Verificar permisos (chmod +x post_deploy.sh)"
echo ""

echo "4️⃣  Problemas con settings_production.py"
echo "   - Django puede estar usando settings.py en vez de settings_production.py"
echo "   - Verificar variable de entorno DJANGO_SETTINGS_MODULE"
echo ""

echo "5️⃣  El usuario existe pero la contraseña está mal"
echo "   - Si cambiaste la contraseña localmente, NO afecta a Render"
echo "   - Render crea el usuario desde cero con post_deploy.sh"
echo ""

echo "============================================================"
echo "🛠️  SOLUCIONES:"
echo "============================================================"
echo ""

echo "OPCIÓN A: Verificar en Render Shell (RECOMENDADO)"
echo "----------"
echo "1. Ve a tu servicio en Render Dashboard"
echo "2. Haz clic en 'Shell' en el menú lateral"
echo "3. Ejecuta estos comandos:"
echo ""
echo "   cd soptraloc_system"
echo "   python manage.py shell --settings=config.settings_production"
echo ""
echo "   Luego en el shell de Python:"
echo "   >>> from django.contrib.auth.models import User"
echo "   >>> User.objects.all().count()"
echo "   >>> User.objects.filter(username='admin').exists()"
echo "   >>> admin = User.objects.get(username='admin')"
echo "   >>> admin.check_password('1234')"
echo ""

echo "OPCIÓN B: Crear usuario manualmente en Render Shell"
echo "----------"
echo "Si el usuario NO existe, créalo:"
echo ""
echo "   cd soptraloc_system"
echo "   python manage.py createsuperuser --settings=config.settings_production"
echo ""
echo "   Username: admin"
echo "   Email: admin@soptraloc.com"
echo "   Password: 1234"
echo "   Password (again): 1234"
echo ""

echo "OPCIÓN C: Forzar re-deploy con post_deploy.sh"
echo "----------"
echo "1. Agregar un comentario vacío en cualquier archivo"
echo "2. Hacer commit y push"
echo "3. Render detectará el cambio y hará re-deploy"
echo "4. Verificar logs de deploy para confirmar que post_deploy.sh se ejecutó"
echo ""

echo "OPCIÓN D: Resetear la contraseña desde Render Shell"
echo "----------"
echo "   cd soptraloc_system"
echo "   python manage.py shell --settings=config.settings_production"
echo ""
echo "   >>> from django.contrib.auth.models import User"
echo "   >>> admin = User.objects.get(username='admin')"
echo "   >>> admin.set_password('1234')"
echo "   >>> admin.save()"
echo "   >>> print('Password cambiada a: 1234')"
echo ""

echo "============================================================"
echo "📊 INFORMACIÓN ADICIONAL:"
echo "============================================================"
echo ""
echo "Base de datos actual (LOCAL): SQLite"
echo "Base de datos en Render: PostgreSQL"
echo ""
echo "Credenciales configuradas en post_deploy.sh:"
echo "  Usuario: admin"
echo "  Password: 1234"
echo ""
echo "URL de admin en Render:"
echo "  https://soptraloc.onrender.com/admin/"
echo "  (verifica en Render Dashboard si es diferente)"
echo ""

echo "============================================================"
echo "🔍 SIGUIENTE PASO:"
echo "============================================================"
echo ""
echo "1. Accede al Shell de Render"
echo "2. Verifica si el usuario existe"
echo "3. Si no existe, créalo manualmente"
echo "4. Si existe pero la contraseña no funciona, resetéala"
echo ""
echo "============================================================"
