# Generated by Django 5.1.4 on 2026-07-19 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cds', '0003_cd_geocerca_radio_m'),
        ('containers', '0010_repair_all_container_columns'),
        ('programaciones', '0009_programacion_fecha_liberacion_conductor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('hora_inicio_recepcion', models.TimeField(default='08:00')),
                ('hora_fin_recepcion', models.TimeField(default='18:00')),
                ('duracion_slot_min', models.PositiveIntegerField(default=60)),
                ('capacidad_por_slot', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa cliente',
                'verbose_name_plural': 'Empresas cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_solicitar', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='clientes.clienteempresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario cliente',
                'verbose_name_plural': 'Usuarios cliente',
            },
        ),
        migrations.CreateModel(
            name='SolicitudHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('recomendado', 'Recomendado'), ('manual', 'Manual')], max_length=12)),
                ('inicio_solicitado', models.DateTimeField(db_index=True)),
                ('fin_solicitado', models.DateTimeField()),
                ('recomendacion_snapshot', models.JSONField(blank=True, default=dict)),
                ('observaciones_cliente', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('ajustada', 'Ajustada por Operaciones'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=12)),
                ('inicio_confirmado', models.DateTimeField(blank=True, null=True)),
                ('fin_confirmado', models.DateTimeField(blank=True, null=True)),
                ('respuesta_operaciones', models.TextField(blank=True)),
                ('revisado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_horario', to='cds.cd')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_horario', to='containers.container')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='clientes.clienteempresa')),
                ('programacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_cliente', to='programaciones.programacion')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cliente_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='clientes_so_empresa_333a28_idx'), models.Index(fields=['inicio_solicitado'], name='clientes_so_inicio__8956c3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('container',), name='unique_pending_request_per_container')],
            },
        ),
    ]
