# Generated by Django 5.2.6 on 2025-10-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0014_alter_location_id_alter_location_table"),
        ("routing", "0002_alter_actualoperationrecord_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualoperationrecord",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_records",
                to="drivers.location",
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips_to",
                to="drivers.location",
                verbose_name="Destino",
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drivers.driver",
                verbose_name="Conductor",
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips_from",
                to="drivers.location",
                verbose_name="Origen",
            ),
        ),
        migrations.AlterField(
            model_name="locationpair",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_to",
                to="drivers.location",
                verbose_name="Destino",
            ),
        ),
        migrations.AlterField(
            model_name="locationpair",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_from",
                to="drivers.location",
                verbose_name="Origen",
            ),
        ),
        migrations.AlterField(
            model_name="operationtime",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_times",
                to="drivers.location",
                verbose_name="Ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="drivers.driver",
                verbose_name="Conductor",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="drivers.location",
                verbose_name="Ubicación",
            ),
        ),
    ]
