# Generated by Django 5.2.6 on 2025-10-09 22:29
# FIXED: Maneja transición de core.driver/location a drivers.driver/location

import django.db.models.deletion
from django.db import migrations, models


def safe_alter_fks(apps, schema_editor):
    """
    Altera FKs de forma segura manejando cambios de tipo en PostgreSQL.
    """
    vendor = schema_editor.connection.vendor
    
    if vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            # Limpiar registros huérfanos antes de cambiar FKs
            
            # ActualTripRecord
            cursor.execute("""
                UPDATE routing_actualtriprecord 
                SET driver_id = NULL 
                WHERE driver_id IS NOT NULL
                AND driver_id::text NOT IN (SELECT id::text FROM drivers);
            """)
            
            # Route
            cursor.execute("""
                DELETE FROM routing_route
                WHERE driver_id IS NOT NULL
                AND driver_id::text NOT IN (SELECT id::text FROM drivers);
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0014_alter_location_id_alter_location_table"),
        ("routing", "0002_alter_actualoperationrecord_location_and_more"),
    ]

    operations = [
        # Primero limpiamos datos
        migrations.RunPython(safe_alter_fks, reverse_code=migrations.RunPython.noop),
        
        # Luego alteramos los FKs
        migrations.AlterField(
            model_name="actualoperationrecord",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_records",
                to="drivers.location",
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips_to",
                to="drivers.location",
                verbose_name="Destino",
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drivers.driver",
                verbose_name="Conductor",
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips_from",
                to="drivers.location",
                verbose_name="Origen",
            ),
        ),
        migrations.AlterField(
            model_name="locationpair",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_to",
                to="drivers.location",
                verbose_name="Destino",
            ),
        ),
        migrations.AlterField(
            model_name="locationpair",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_from",
                to="drivers.location",
                verbose_name="Origen",
            ),
        ),
        migrations.AlterField(
            model_name="operationtime",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_times",
                to="drivers.location",
                verbose_name="Ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="drivers.driver",
                verbose_name="Conductor",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="drivers.location",
                verbose_name="Ubicación",
            ),
        ),
    ]
