# Generated by Django 5.1.4 on 2025-10-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routing", "0004_reset_routing_for_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualtriprecord",
            name="arrival_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Hora de llegada"
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="departure_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Hora de salida"
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="duration_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Calculado automáticamente",
                null=True,
                verbose_name="Duración en minutos",
            ),
        ),
    ]
