# Generated by Django 5.1.4 on 2025-10-10 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0019_alter_location_options"),
        ("routing", "0005_alter_actualtriprecord_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualoperationrecord",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_records",
                to="drivers.location",
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips_to",
                to="drivers.location",
                verbose_name="Destino",
            ),
        ),
        migrations.AlterField(
            model_name="actualtriprecord",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips_from",
                to="drivers.location",
                verbose_name="Origen",
            ),
        ),
        migrations.AlterField(
            model_name="locationpair",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_to",
                to="drivers.location",
                verbose_name="Destino",
            ),
        ),
        migrations.AlterField(
            model_name="locationpair",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_from",
                to="drivers.location",
                verbose_name="Origen",
            ),
        ),
        migrations.AlterField(
            model_name="operationtime",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_times",
                to="drivers.location",
                verbose_name="Ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="drivers.location",
                verbose_name="Ubicación",
            ),
        ),
    ]
