# Generated by Django 5.1.4 on 2025-10-11 14:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Nombre"
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="RUT",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "presente",
                    models.BooleanField(
                        default=True,
                        help_text="¿Está disponible hoy?",
                        verbose_name="Presente",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "cumplimiento_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Porcentaje de entregas a tiempo",
                        max_digits=5,
                        verbose_name="Cumplimiento (%)",
                    ),
                ),
                (
                    "num_entregas_dia",
                    models.IntegerField(default=0, verbose_name="Entregas del Día"),
                ),
                (
                    "max_entregas_dia",
                    models.IntegerField(default=3, verbose_name="Max Entregas/Día"),
                ),
                (
                    "ultima_posicion_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "ultima_posicion_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "ultima_actualizacion_posicion",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Última Actualización Posición",
                    ),
                ),
                (
                    "total_entregas",
                    models.IntegerField(default=0, verbose_name="Total Entregas"),
                ),
                (
                    "entregas_a_tiempo",
                    models.IntegerField(default=0, verbose_name="Entregas a Tiempo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Conductor",
                "verbose_name_plural": "Conductores",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="drivers_dri_nombre_bd22de_idx"
                    ),
                    models.Index(
                        fields=["presente", "activo"],
                        name="drivers_dri_present_88228c_idx",
                    ),
                ],
            },
        ),
    ]
