# Generated by Django 5.1.4 on 2025-10-12 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Precisión (metros)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha/Hora')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='drivers.driver', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Ubicación del Conductor',
                'verbose_name_plural': 'Ubicaciones de Conductores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', '-timestamp'], name='drivers_dri_driver__edda82_idx')],
            },
        ),
    ]
