# Generated by Django 5.1.4 on 2025-10-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_user_driverlocation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driverlocation',
            new_name='drivers_dri_timesta_eb0b05_idx',
            old_name='drivers_dri_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='driverlocation',
            new_name='drivers_dri_driver__edda82_idx',
            old_name='drivers_dri_driver_timesta_idx',
        ),
    ]
