# Generated by Django 6.1.1 on 2026-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_driver_patente"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="capacidad_ton",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Capacidad real del camión; si se deja vacío se usa 28 en el scoring.",
                max_digits=5,
                null=True,
                verbose_name="Capacidad Vehículo (ton)",
            ),
        ),
    ]
