# Generated by Django 5.1.4 on 2026-10-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0005_driver_capacidad_ton"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="excluir_ml",
            field=models.BooleanField(
                default=False,
                help_text="Si True: sus viajes/operaciones NO alimentan el motor de aprendizaje (conductores de prueba o demo).",
                verbose_name="Excluir del ML",
            ),
        ),
    ]
