# Generated by Django 5.1.4 on 2025-10-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cds", "0001_initial"),
        ("containers", "0001_initial"),
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(
                        db_index=True, verbose_name="Fecha Programada"
                    ),
                ),
                ("cliente", models.CharField(max_length=200, verbose_name="Cliente")),
                (
                    "direccion_entrega",
                    models.TextField(blank=True, verbose_name="Dirección Entrega"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "eta_minutos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ETA (minutos)"
                    ),
                ),
                (
                    "distancia_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distancia (km)",
                    ),
                ),
                (
                    "ruta_geojson",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Ruta GeoJSON"
                    ),
                ),
                (
                    "alerta_48h_enviada",
                    models.BooleanField(
                        default=False, verbose_name="Alerta 48h Enviada"
                    ),
                ),
                (
                    "requiere_alerta",
                    models.BooleanField(default=False, verbose_name="Requiere Alerta"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programaciones",
                        to="cds.cd",
                        verbose_name="Centro de Distribución",
                    ),
                ),
                (
                    "container",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programacion",
                        to="containers.container",
                        verbose_name="Contenedor",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programaciones",
                        to="drivers.driver",
                        verbose_name="Conductor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programación",
                "verbose_name_plural": "Programaciones",
                "ordering": ["fecha_programada"],
                "indexes": [
                    models.Index(
                        fields=["fecha_programada"],
                        name="programacio_fecha_p_007d8e_idx",
                    ),
                    models.Index(
                        fields=["alerta_48h_enviada", "requiere_alerta"],
                        name="programacio_alerta__e26823_idx",
                    ),
                    models.Index(
                        fields=["driver"], name="programacio_driver__b7ad5d_idx"
                    ),
                ],
            },
        ),
    ]
