# Generated by Django 5.1.4 on 2025-10-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0002_cd_permite_soltar_contenedor_and_more"),
        (
            "containers",
            "0002_container_cd_entrega_container_deposito_devolucion_and_more",
        ),
        ("drivers", "0001_initial"),
        ("programaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiempoOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_operacion",
                    models.CharField(
                        choices=[
                            ("carga_ccti", "Carga en CCTI"),
                            ("descarga_cd", "Descarga en CD"),
                            ("retiro_puerto", "Retiro en Puerto"),
                            ("devolucion_vacio", "Devolución Vacío"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tiempo_estimado_min",
                    models.IntegerField(
                        help_text="Tiempo estimado inicial (ej: CD.tiempo_promedio_descarga_min)"
                    ),
                ),
                (
                    "tiempo_real_min",
                    models.IntegerField(
                        help_text="Tiempo real medido desde hora_inicio hasta hora_fin"
                    ),
                ),
                ("hora_inicio", models.DateTimeField()),
                ("hora_fin", models.DateTimeField()),
                ("fecha", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "anomalia",
                    models.BooleanField(
                        default=False,
                        help_text="Marca tiempos anómalos (>3x estimado) para excluir del aprendizaje",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempos_operacion",
                        to="cds.cd",
                    ),
                ),
                (
                    "conductor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drivers.driver",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiempo de Operación",
                "verbose_name_plural": "Tiempos de Operación",
                "ordering": ["-fecha", "-hora_inicio"],
                "indexes": [
                    models.Index(
                        fields=["cd", "tipo_operacion", "-fecha"],
                        name="programacio_cd_id_cac36d_idx",
                    ),
                    models.Index(
                        fields=["conductor", "-fecha"],
                        name="programacio_conduct_eea4b8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TiempoViaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origen_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("origen_lon", models.DecimalField(decimal_places=7, max_digits=10)),
                ("destino_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("destino_lon", models.DecimalField(decimal_places=7, max_digits=10)),
                ("origen_nombre", models.CharField(blank=True, max_length=200)),
                ("destino_nombre", models.CharField(blank=True, max_length=200)),
                (
                    "tiempo_mapbox_min",
                    models.IntegerField(
                        help_text="Tiempo estimado por Mapbox al iniciar viaje"
                    ),
                ),
                (
                    "tiempo_real_min",
                    models.IntegerField(
                        help_text="Tiempo real medido desde salida hasta llegada"
                    ),
                ),
                ("hora_salida", models.DateTimeField()),
                ("hora_llegada", models.DateTimeField()),
                ("fecha", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "hora_del_dia",
                    models.IntegerField(
                        help_text="Hora de salida (0-23) para análisis de tráfico"
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        help_text="Día de la semana (0=Lunes, 6=Domingo)"
                    ),
                ),
                (
                    "distancia_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distancia en km según Mapbox",
                        max_digits=7,
                    ),
                ),
                (
                    "anomalia",
                    models.BooleanField(
                        default=False,
                        help_text="Marca viajes anómalos (pausas largas, desvíos) para excluir",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "conductor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drivers.driver",
                    ),
                ),
                (
                    "programacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="programaciones.programacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiempo de Viaje",
                "verbose_name_plural": "Tiempos de Viaje",
                "ordering": ["-fecha", "-hora_salida"],
                "indexes": [
                    models.Index(
                        fields=[
                            "origen_lat",
                            "origen_lon",
                            "destino_lat",
                            "destino_lon",
                        ],
                        name="programacio_origen__131ef1_idx",
                    ),
                    models.Index(
                        fields=["hora_del_dia", "dia_semana"],
                        name="programacio_hora_de_31435e_idx",
                    ),
                    models.Index(
                        fields=["conductor", "-fecha"],
                        name="programacio_conduct_5bea9f_idx",
                    ),
                ],
            },
        ),
    ]
