# Generated by Django 5.1.4 on 2025-10-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0002_tiempooperacion_tiempoviaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Asignación'),
        ),
    ]
