# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0004_programacion_ruta_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='aceptada_por_conductor',
            field=models.BooleanField(default=False, help_text='Indica si el conductor aceptó la asignación', verbose_name='Aceptada por Conductor'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el conductor aceptó la asignación', null=True, verbose_name='Fecha Aceptación'),
        ),
    ]
