# Generated by Django 5.1.4 on 2025-11-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0004_programacion_ruta_fields'),
    ]

    operations = [
        # Índices para mejorar performance de queries frecuentes
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS programaciones_programacion_driver_null_idx 
            ON programaciones_programacion (id) 
            WHERE driver_id IS NULL;
            
            CREATE INDEX IF NOT EXISTS programaciones_programacion_estado_container_idx 
            ON programaciones_programacion (container_id, fecha_programada);
            
            CREATE INDEX IF NOT EXISTS programaciones_tiempoviaje_lookup_idx 
            ON programaciones_tiempoviaje (origen_lat, origen_lon, destino_lat, destino_lon, anomalia, fecha)
            WHERE anomalia = false;
            
            CREATE INDEX IF NOT EXISTS programaciones_tiempooperacion_lookup_idx 
            ON programaciones_tiempooperacion (cd_id, tipo_operacion, anomalia, fecha)
            WHERE anomalia = false;
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS programaciones_programacion_driver_null_idx;
            DROP INDEX IF EXISTS programaciones_programacion_estado_container_idx;
            DROP INDEX IF EXISTS programaciones_tiempoviaje_lookup_idx;
            DROP INDEX IF EXISTS programaciones_tiempooperacion_lookup_idx;
            """
        ),
    ]
