# Generated by Django 5.1.4 on 2026-04-25 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0004_programacion_ruta_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='anomalias_detectadas',
            field=models.JSONField(blank=True, default=list, verbose_name='Anomalías Detectadas'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='clasificacion_sistema',
            field=models.CharField(choices=[('DESPACHO_DIRECTO', '🟢 Despacho Directo'), ('REVISION_OPERADOR', '🟡 Revisión Operador'), ('INTERVENCION', '🔴 Intervención')], default='REVISION_OPERADOR', max_length=20, verbose_name='Clasificación del Sistema'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='decision_operador',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMAR', 'Confirmar'), ('RECHAZAR', 'Rechazar'), ('MODIFICAR', 'Modificar'), ('ESCALAR', 'Escalar')], default='PENDIENTE', max_length=12, verbose_name='Decisión Operador'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='desviaciones_detectadas',
            field=models.JSONField(blank=True, default=list, verbose_name='Desviaciones Detectadas'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='estado_final',
            field=models.CharField(blank=True, choices=[('ENTREGADO', 'Entregado'), ('PARCIAL', 'Parcial'), ('FALLIDO', 'Fallido')], max_length=10, null=True, verbose_name='Estado Final'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='eta_estimado_cierre_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='ETA Estimado al Cierre (min)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='eta_real_cierre_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='ETA Real al Cierre (min)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='eta_recalculado_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='ETA Recalculado (min)'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='incidentes_registrados',
            field=models.JSONField(blank=True, default=list, verbose_name='Incidentes Registrados'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='motivo_override',
            field=models.TextField(blank=True, verbose_name='Motivo Override'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='nivel_confianza',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Nivel de Confianza'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='posicion_actual_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Posición Actual Lat'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='posicion_actual_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Posición Actual Lng'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='requiere_seguimiento_especial',
            field=models.BooleanField(default=False, verbose_name='Requiere Seguimiento Especial'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='score_por_dimension',
            field=models.JSONField(blank=True, default=dict, verbose_name='Score por Dimensión'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='similitud_historica_usada',
            field=models.JSONField(blank=True, default=list, verbose_name='Similitud Histórica Usada'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='timestamp_despacho',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp Despacho'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='ultima_actualizacion_tracking',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización Tracking'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='urgencia_servicio',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('CRITICO', 'Crítico')], default='NORMAL', max_length=10, verbose_name='Urgencia del Servicio'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='ventana_horaria_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ventana Horaria Fin'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='ventana_horaria_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ventana Horaria Inicio'),
        ),
        migrations.CreateModel(
            name='RegistroOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100)),
                ('recurso_asignado', models.CharField(blank=True, max_length=200)),
                ('score_por_dimension', models.JSONField(blank=True, default=dict)),
                ('clasificacion_sistema', models.CharField(choices=[('DESPACHO_DIRECTO', '🟢 Despacho Directo'), ('REVISION_OPERADOR', '🟡 Revisión Operador'), ('INTERVENCION', '🔴 Intervención')], max_length=20)),
                ('decision_operador', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMAR', 'Confirmar'), ('RECHAZAR', 'Rechazar'), ('MODIFICAR', 'Modificar'), ('ESCALAR', 'Escalar')], default='PENDIENTE', max_length=12)),
                ('motivo_override', models.TextField(blank=True)),
                ('anomalias_detectadas', models.JSONField(blank=True, default=list)),
                ('similitud_historica_usada', models.JSONField(blank=True, default=list)),
                ('timestamp_despacho', models.DateTimeField(default=django.utils.timezone.now)),
                ('eta_estimado_min', models.IntegerField(blank=True, null=True)),
                ('eta_real_min', models.IntegerField(blank=True, null=True)),
                ('incidentes_ejecucion', models.JSONField(blank=True, default=list)),
                ('estado_final', models.CharField(blank=True, choices=[('ENTREGADO', 'Entregado'), ('PARCIAL', 'Parcial'), ('FALLIDO', 'Fallido')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_operacion', to='programaciones.programacion')),
            ],
            options={
                'verbose_name': 'Registro Operación',
                'verbose_name_plural': 'Registros Operación',
                'ordering': ['-created_at'],
            },
        ),
    ]
