# Generated by Django 5.1.4 on 2026-07-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0005_programacion_anomalias_detectadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='fecha_arribo_cd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Arribo CD'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='gps_arribo_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Arribo Latitud'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='gps_arribo_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Arribo Longitud'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='origen_arribo',
            field=models.CharField(blank=True, choices=[('manual', 'Manual conductor'), ('geocerca', 'Geocerca')], max_length=20, null=True, verbose_name='Origen Arribo'),
        ),
    ]
