# Generated by Django 5.1.4 on 2026-07-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0006_programacion_fecha_arribo_cd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='ruta_firma',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Firma Ruta'),
        ),
        migrations.AddField(
            model_name='tiempoviaje',
            name='ruta_firma',
            field=models.CharField(blank=True, db_index=True, help_text='Huella estable de la geometría utilizada para aprender diferencias entre rutas.', max_length=64, null=True),
        ),
    ]
