# Generated by Django 5.1.4 on 2026-07-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0007_programacion_ruta_firma_tiempoviaje_ruta_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='prediccion_ml',
            field=models.JSONField(blank=True, default=dict, help_text='Fuente, muestras, factor y confianza usados para estimar el viaje.', verbose_name='Predicción ML auditable'),
        ),
    ]
