# Generated by Django 5.1.4 on 2026-07-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0008_programacion_prediccion_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='fecha_liberacion_conductor',
            field=models.DateTimeField(blank=True, help_text='Momento en que el conductor quedó realmente disponible para otro servicio.', null=True, verbose_name='Fecha Liberación Conductor'),
        ),
    ]
