# Generated by Django 6.1.1 on 2026-09-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0003_cd_geocerca_radio_m"),
        (
            "containers",
            "0009_container_fecha_cancelado_container_fecha_en_ccti_and_more",
        ),
        ("drivers", "0005_driver_capacidad_ton"),
        ("programaciones", "0009_programacion_fecha_liberacion_conductor"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="programacion",
            index=models.Index(
                fields=["driver", "fecha_liberacion_conductor"],
                name="prog_driver_vigencia_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="programacion",
            index=models.Index(
                fields=["container", "driver"], name="prog_container_driver_idx"
            ),
        ),
    ]
