# Generated by Django 5.1.4 on 2026-10-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programaciones", "0011_programacion_fecha_inicio_descarga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiempooperacion",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("carga_patio", "Carga en Patio"),
                    ("descarga_cd", "Descarga en CD"),
                    ("retiro_puerto", "Retiro en Puerto"),
                    ("devolucion_vacio", "Devolución Vacío"),
                ],
                max_length=20,
            ),
        ),
    ]
