#!/bin/bash

echo "🗂️  GUÍA DE GESTIÓN DE ARCHIVOS - SOPTRALOC"
echo "=========================================="
echo ""

echo "📍 UBICACIÓN ACTUAL:"
echo "Proyecto: $(pwd)"
echo "Usuario: $(whoami)"
echo "Sistema: $(uname -a | cut -d' ' -f1-3)"
echo ""

echo "📁 ESTRUCTURA DEL PROYECTO:"
echo "================================"
tree -L 3 /workspaces/soptraloc/ 2>/dev/null || find /workspaces/soptraloc/ -type d -maxdepth 3 | head -20

echo ""
echo "🔧 COMANDOS BÁSICOS DE ARCHIVOS:"
echo "================================"
echo ""
echo "📝 EDITAR ARCHIVOS:"
echo "   nano archivo.py          # Editor simple"
echo "   vim archivo.py           # Editor avanzado" 
echo "   code archivo.py          # VS Code"
echo ""
echo "📋 VER CONTENIDO:"
echo "   cat archivo.py           # Mostrar archivo completo"
echo "   head -20 archivo.py      # Primeras 20 líneas"
echo "   tail -20 archivo.py      # Últimas 20 líneas"
echo "   less archivo.py          # Ver archivo paginado"
echo ""
echo "📁 NAVEGACIÓN:"
echo "   ls -la                   # Listar archivos detallado"
echo "   cd /path/to/directory    # Cambiar directorio"
echo "   pwd                      # Mostrar directorio actual"
echo "   find . -name '*.py'      # Buscar archivos Python"
echo ""
echo "📤 TRANSFERIR ARCHIVOS:"
echo "   cp origen destino        # Copiar archivo"
echo "   mv origen destino        # Mover/renombrar archivo"
echo "   rm archivo               # Eliminar archivo"
echo "   mkdir carpeta            # Crear carpeta"
echo ""
echo "🚀 COMANDOS ESPECÍFICOS DJANGO:"
echo "================================"
echo "   python manage.py runserver                    # Iniciar servidor"
echo "   python manage.py shell                        # Shell Django"
echo "   python manage.py makemigrations               # Crear migraciones"
echo "   python manage.py migrate                      # Aplicar migraciones"
echo "   python manage.py collectstatic                # Recopilar archivos estáticos"
echo ""

echo "🔑 ACCESO AL SISTEMA:"
echo "====================="
echo "• VS Code (actual): Navegador de archivos lateral"
echo "• Terminal: $(which bash)"
echo "• Editores: nano, vim, code"
echo "• Permisos: $(id)"

echo ""
echo "📊 ESTADO DEL SERVIDOR:"
echo "======================="
if pgrep -f "python manage.py runserver" > /dev/null; then
    echo "✅ Servidor Django: EJECUTÁNDOSE"
    echo "🌐 URL: http://localhost:8000"
else
    echo "❌ Servidor Django: DETENIDO"
    echo "Para iniciar: python manage.py runserver 0.0.0.0:8000"
fi