# Generated by Django 5.1.4 on 2025-10-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="location",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="movementcode",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transferencia"),
                    ("load", "Carga"),
                    ("unload", "Descarga"),
                    ("return", "Devolución"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
