# Generated by Django 5.1.4 on 2025-10-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Limpieza de metadata obsoleta en core:
    - Location: Cambiar a managed=False (drivers.Location gestiona la tabla)
    - Driver: Eliminar solo metadata (tabla nunca existió en core, siempre estuvo en drivers)
    """

    dependencies = [
        ("core", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "managed": False,
                "verbose_name": "Ubicación (Histórico)",
                "verbose_name_plural": "Ubicaciones (Histórico)",
            },
        ),
        migrations.AlterField(
            model_name="movementcode",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transferencia"),
                    ("load", "Carga"),
                    ("unload", "Descarga"),
                    ("return", "Devolución"),
                ],
                max_length=20,
            ),
        ),
        # DeleteModel solo en estado, NO en base de datos
        # (core_driver nunca existió, Driver siempre estuvo en app drivers)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="Driver"),
            ],
            database_operations=[],  # No hacer nada en DB
        ),
    ]
