# Generated by Django 5.1.4 on 2025-10-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "managed": False,
                "verbose_name": "Ubicación (Histórico)",
                "verbose_name_plural": "Ubicaciones (Histórico)",
            },
        ),
        migrations.AlterField(
            model_name="movementcode",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transferencia"),
                    ("load", "Carga"),
                    ("unload", "Descarga"),
                    ("return", "Devolución"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
    ]
