# Generated by Django 5.1.4 on 2025-10-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table="core_location",
        ),
    ]
