# Generated by Django 5.1.4 on 2025-10-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="ID Contenedor",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("20", "20'"),
                            ("40", "40'"),
                            ("40HC", "40' HC"),
                            ("45", "45'"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("nave", models.CharField(max_length=100, verbose_name="Nave")),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Vendor"
                    ),
                ),
                (
                    "sello",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Sello"
                    ),
                ),
                (
                    "puerto",
                    models.CharField(
                        default="Valparaíso", max_length=100, verbose_name="Puerto"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_arribar", "Por Arribar"),
                            ("liberado", "Liberado"),
                            ("secuenciado", "Secuenciado"),
                            ("programado", "Programado"),
                            ("asignado", "Asignado"),
                            ("en_ruta", "En Ruta"),
                            ("entregado", "Entregado"),
                            ("descargado", "Descargado"),
                            ("en_almacen_ccti", "En Almacén CCTI"),
                            ("vacio_en_ruta", "Vacío en Ruta"),
                            ("vacio_en_ccti", "Vacío en CCTI"),
                        ],
                        db_index=True,
                        default="por_arribar",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "posicion_fisica",
                    models.CharField(
                        blank=True,
                        help_text="TPS, STI, PCE, ZEAL, CLEP, etc.",
                        max_length=100,
                        null=True,
                        verbose_name="Posición Física",
                    ),
                ),
                (
                    "comuna",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Comuna Destino",
                    ),
                ),
                (
                    "secuenciado",
                    models.BooleanField(
                        default=False,
                        help_text="Marcado para próxima liberación",
                        verbose_name="Secuenciado",
                    ),
                ),
                (
                    "fecha_arribo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Arribo"
                    ),
                ),
                (
                    "fecha_liberacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Liberación"
                    ),
                ),
                (
                    "fecha_programacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Programación"
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Asignación"
                    ),
                ),
                (
                    "fecha_inicio_ruta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Inicio Ruta"
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Entrega"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Contenedor",
                "verbose_name_plural": "Contenedores",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["container_id"], name="containers__contain_db6994_idx"
                    ),
                    models.Index(
                        fields=["estado"], name="containers__estado_d7d65f_idx"
                    ),
                    models.Index(
                        fields=["fecha_programacion"],
                        name="containers__fecha_p_9268d8_idx",
                    ),
                    models.Index(
                        fields=["secuenciado"], name="containers__secuenc_19d001_idx"
                    ),
                ],
            },
        ),
    ]
