# Generated by Django 5.1.4 on 2025-10-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0002_cd_permite_soltar_contenedor_and_more"),
        ("containers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="cd_entrega",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contenedores_entregados",
                to="cds.cd",
                verbose_name="CD de Entrega",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="deposito_devolucion",
            field=models.CharField(
                blank=True,
                help_text="Dónde devolver contenedor vacío",
                max_length=200,
                null=True,
                verbose_name="Depósito Devolución",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_demurrage",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha de vencimiento de demurrage (después se paga)",
                null=True,
                verbose_name="Fecha Demurrage",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_eta",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha estimada de arribo",
                null=True,
                verbose_name="ETA (Estimated Time of Arrival)",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="hora_descarga",
            field=models.DateTimeField(
                blank=True,
                help_text="Hora en que cliente descargó el contenedor",
                null=True,
                verbose_name="Hora Descarga",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("automatico", "Automático (Puerto)"),
                    ("retiro_ccti", "Retiro a CCTI"),
                    ("retiro_directo", "Retiro Directo a Cliente"),
                ],
                default="automatico",
                max_length=20,
                verbose_name="Tipo de Movimiento",
            ),
        ),
    ]
