# Generated by Django 5.1.4 on 2025-10-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "containers",
            "0002_container_cd_entrega_container_deposito_devolucion_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="hora_descarga",
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_descarga",
            field=models.DateTimeField(
                blank=True,
                help_text="Cliente termina de descargar",
                null=True,
                verbose_name="Fecha Descarga",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_devolucion",
            field=models.DateTimeField(
                blank=True,
                help_text="Devuelto a depósito naviera",
                null=True,
                verbose_name="Fecha Devolución",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_vacio",
            field=models.DateTimeField(
                blank=True,
                help_text="Contenedor vacío listo para retiro",
                null=True,
                verbose_name="Fecha Vacío",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_vacio_ruta",
            field=models.DateTimeField(
                blank=True,
                help_text="Iniciando retorno a depósito",
                null=True,
                verbose_name="Fecha Vacío en Ruta",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="estado",
            field=models.CharField(
                choices=[
                    ("por_arribar", "Por Arribar"),
                    ("arribado", "Arribado"),
                    ("liberado", "Liberado"),
                    ("secuenciado", "Secuenciado"),
                    ("programado", "Programado"),
                    ("asignado", "Asignado"),
                    ("en_ruta", "En Ruta"),
                    ("entregado", "Entregado"),
                    ("descargado", "Descargado"),
                    ("vacio", "Vacío"),
                    ("vacio_en_ruta", "Vacío en Ruta"),
                    ("devuelto", "Devuelto"),
                ],
                db_index=True,
                default="por_arribar",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="fecha_arribo",
            field=models.DateTimeField(
                blank=True,
                help_text="Nave llega a puerto",
                null=True,
                verbose_name="Fecha Arribo",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="fecha_asignacion",
            field=models.DateTimeField(
                blank=True,
                help_text="Asignado a conductor",
                null=True,
                verbose_name="Fecha Asignación",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="fecha_entrega",
            field=models.DateTimeField(
                blank=True,
                help_text="Llega a CD cliente",
                null=True,
                verbose_name="Fecha Entrega",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="fecha_inicio_ruta",
            field=models.DateTimeField(
                blank=True,
                help_text="Conductor sale con contenedor",
                null=True,
                verbose_name="Fecha Inicio Ruta",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="fecha_liberacion",
            field=models.DateTimeField(
                blank=True,
                help_text="Liberado por aduana/naviera",
                null=True,
                verbose_name="Fecha Liberación",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="fecha_programacion",
            field=models.DateTimeField(
                blank=True,
                help_text="Asignado a fecha y CD",
                null=True,
                verbose_name="Fecha Programación",
            ),
        ),
    ]
