# Generated by Django 5.1.4 on 2025-10-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0003_add_estados_completos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="peso",
        ),
        migrations.AddField(
            model_name="container",
            name="contenido",
            field=models.TextField(
                blank=True,
                help_text="Descripción de la carga",
                null=True,
                verbose_name="Contenido",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="peso_carga",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso de la mercancía",
                max_digits=10,
                null=True,
                verbose_name="Peso Carga (kg)",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tara",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso del contenedor vacío",
                max_digits=10,
                null=True,
                verbose_name="Tara (kg)",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="tipo_carga",
            field=models.CharField(
                choices=[
                    ("dry", "Dry (Seco)"),
                    ("reefer", "Reefer (Refrigerado)"),
                    ("open_top", "Open Top"),
                    ("flat_rack", "Flat Rack"),
                    ("tank", "Tank"),
                ],
                default="dry",
                max_length=20,
                verbose_name="Tipo de Carga",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="estado",
            field=models.CharField(
                choices=[
                    ("por_arribar", "Por Arribar"),
                    ("liberado", "Liberado"),
                    ("secuenciado", "Secuenciado"),
                    ("programado", "Programado"),
                    ("asignado", "Asignado"),
                    ("en_ruta", "En Ruta"),
                    ("entregado", "Entregado"),
                    ("descargado", "Descargado"),
                    ("vacio", "Vacío"),
                    ("vacio_en_ruta", "Vacío en Ruta"),
                    ("devuelto", "Devuelto"),
                ],
                db_index=True,
                default="por_arribar",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
