# Generated by Django 5.1.4 on 2025-10-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0004_add_peso_contenido_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="booking",
            field=models.CharField(
                blank=True,
                help_text="Número de booking o Master Bill of Lading",
                max_length=100,
                null=True,
                verbose_name="Booking/MBL",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="cliente",
            field=models.CharField(
                blank=True,
                help_text="Nombre del cliente final",
                max_length=200,
                null=True,
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="referencia",
            field=models.CharField(
                blank=True,
                help_text="Referencia del cliente",
                max_length=100,
                null=True,
                verbose_name="Referencia",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="viaje",
            field=models.CharField(
                blank=True,
                help_text="Número de viaje",
                max_length=50,
                null=True,
                verbose_name="Viaje",
            ),
        ),
    ]
