# Generated by Django 5.1.4 on 2026-07-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_container_business_state_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='fecha_soltado',
            field=models.DateTimeField(blank=True, help_text='Drop & hook: conductor deja el contenedor aún lleno', null=True, verbose_name='Fecha Soltado'),
        ),
        migrations.AlterField(
            model_name='container',
            name='estado',
            field=models.CharField(choices=[('por_arribar', 'Por Arribar'), ('liberado', 'Liberado'), ('secuenciado', 'Secuenciado'), ('programado', 'Programado'), ('asignado', 'Asignado'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('soltado', 'Soltado en CD'), ('descargado', 'Descargado'), ('vacio', 'Vacío'), ('vacio_en_ruta', 'Vacío en Ruta'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado'), ('incidente', 'Incidente')], db_index=True, default='por_arribar', max_length=20, verbose_name='Estado'),
        ),
    ]
