# Generated by Django 5.1.4 on 2026-07-19 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0003_cd_geocerca_radio_m'),
        ('containers', '0007_container_fecha_soltado_alter_container_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='retorno_destino_cd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retornos_vacios_recibidos', to='cds.cd', verbose_name='CCTI destino retorno'),
        ),
        migrations.AddField(
            model_name='container',
            name='retorno_destino_tipo',
            field=models.CharField(blank=True, choices=[('deposito', 'Depósito naviera'), ('ccti', 'CCTI')], max_length=12, null=True, verbose_name='Tipo destino retorno'),
        ),
        migrations.AlterField(
            model_name='container',
            name='estado',
            field=models.CharField(choices=[('por_arribar', 'Por Arribar'), ('liberado', 'Liberado'), ('secuenciado', 'Secuenciado'), ('programado', 'Programado'), ('asignado', 'Asignado'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('soltado', 'Soltado en CD'), ('descargado', 'Descargado'), ('vacio', 'Vacío'), ('vacio_en_ruta', 'Vacío en Ruta'), ('en_ccti', 'Vacío en CCTI'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado'), ('incidente', 'Incidente')], db_index=True, default='por_arribar', max_length=20, verbose_name='Estado'),
        ),
    ]
