# Generated by Django 6.1.1 on 2026-09-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0008_container_retorno_destino_cd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="fecha_cancelado",
            field=models.DateTimeField(
                blank=True,
                help_text="Registrado cuando el contenedor entra a estado cancelado",
                null=True,
                verbose_name="Fecha Cancelación",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_en_ccti",
            field=models.DateTimeField(
                blank=True,
                help_text="Registrado cuando el contenedor vacío ingresa a CCTI",
                null=True,
                verbose_name="Fecha En CCTI",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_incidente",
            field=models.DateTimeField(
                blank=True,
                help_text="Registrado cuando el contenedor entra a estado incidente",
                null=True,
                verbose_name="Fecha Incidente",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_secuenciado",
            field=models.DateTimeField(
                blank=True,
                help_text="Registrado cuando el contenedor entra a estado secuenciado",
                null=True,
                verbose_name="Fecha Secuenciado",
            ),
        ),
    ]
