# Generated by Django 6.1.1 on 2026-09-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0003_cd_geocerca_radio_m"),
        (
            "containers",
            "0009_container_fecha_cancelado_container_fecha_en_ccti_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["estado", "fecha_demurrage"], name="cont_estado_demurrage_idx"
            ),
        ),
    ]
