# Generated by Django 5.1.4 on 2026-07-19 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('containers', '0010_repair_all_container_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='cliente_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contenedores', to='clientes.clienteempresa', verbose_name='Empresa cliente'),
        ),
    ]
