# Generated by Django 6.1.1 on 2026-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0003_cd_geocerca_radio_m"),
        ("containers", "0010_cont_estado_demurrage_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["cliente", "estado"], name="cont_cliente_estado_idx"
            ),
        ),
    ]
