# Generated by Django 6.1.1 on 2026-09-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0011_add_container_cliente_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "aliases",
                    models.CharField(
                        blank=True,
                        help_text="Nombres alternativos separados por coma (normalización de texto libre)",
                        max_length=500,
                        null=True,
                        verbose_name="Aliases",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Depósito",
                "verbose_name_plural": "Depósitos",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="container",
            name="estado_verificado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("por_arribar", "Por Arribar"),
                    ("liberado", "Liberado"),
                    ("secuenciado", "Secuenciado"),
                    ("programado", "Programado"),
                    ("asignado", "Asignado"),
                    ("en_ruta", "En Ruta"),
                    ("entregado", "Entregado"),
                    ("soltado", "Soltado en CD"),
                    ("descargado", "Descargado"),
                    ("vacio", "Vacío"),
                    ("vacio_en_ruta", "Vacío en Ruta"),
                    ("en_ccti", "Vacío en CCTI"),
                    ("devuelto", "Devuelto"),
                    ("cancelado", "Cancelado"),
                    ("incidente", "Incidente"),
                ],
                help_text="Último estado confirmado por fuente externa",
                max_length=20,
                null=True,
                verbose_name="Estado Verificado",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="fuente_verificacion",
            field=models.CharField(
                blank=True,
                help_text="Fuente externa que informó el estado verificado (portal, operador)",
                max_length=200,
                null=True,
                verbose_name="Fuente de Verificación",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="verificado_en",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento de la última verificación externa",
                null=True,
                verbose_name="Verificado En",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="deposito_verificado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contenedores_verificados",
                to="containers.deposit",
                verbose_name="Depósito Verificado",
            ),
        ),
        migrations.CreateModel(
            name="EvidenceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="evidencias/%Y/%m/", verbose_name="Archivo"
                    ),
                ),
                (
                    "md5",
                    models.CharField(db_index=True, max_length=32, verbose_name="MD5"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("eir_in", "EIR Ingreso"),
                            ("eir_out", "EIR Devolución"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del emisor (depósito/portal) que emitió el documento",
                        max_length=200,
                        null=True,
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "fecha_programacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de programación/viaje al que corresponde la evidencia",
                        null=True,
                        verbose_name="Fecha Programación",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Subido"),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Subido por"
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="containers.container",
                        verbose_name="Contenedor",
                    ),
                ),
                (
                    "duplicado_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicados",
                        to="containers.evidencedocument",
                        verbose_name="Duplicado de",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Evidencia",
                "verbose_name_plural": "Documentos de Evidencia",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["container", "tipo"],
                        name="containers__contain_2d992b_idx",
                    ),
                    models.Index(
                        fields=["container", "md5"],
                        name="containers__contain_01b2c0_idx",
                    ),
                ],
            },
        ),
    ]
