# Generated by Django 5.1.4 on 2026-10-03 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0004_alter_cd_permite_soltar_contenedor_and_more"),
        ("containers", "0013_poblar_deposit_catalogo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="fecha_en_ccti",
        ),
        migrations.AddField(
            model_name="container",
            name="fecha_en_patio",
            field=models.DateTimeField(
                blank=True,
                help_text="Registrado cuando el contenedor vacío ingresa al patio propio",
                null=True,
                verbose_name="Fecha En Patio",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="estado",
            field=models.CharField(
                choices=[
                    ("por_arribar", "Por Arribar"),
                    ("liberado", "Liberado"),
                    ("secuenciado", "Secuenciado"),
                    ("programado", "Programado"),
                    ("asignado", "Asignado"),
                    ("en_ruta", "En Ruta"),
                    ("entregado", "Entregado"),
                    ("soltado", "Soltado en CD"),
                    ("descargado", "Descargado"),
                    ("vacio", "Vacío"),
                    ("vacio_en_ruta", "Vacío en Ruta"),
                    ("en_patio", "Vacío en Patio"),
                    ("devuelto", "Devuelto"),
                    ("cancelado", "Cancelado"),
                    ("incidente", "Incidente"),
                ],
                db_index=True,
                default="por_arribar",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="estado_verificado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("por_arribar", "Por Arribar"),
                    ("liberado", "Liberado"),
                    ("secuenciado", "Secuenciado"),
                    ("programado", "Programado"),
                    ("asignado", "Asignado"),
                    ("en_ruta", "En Ruta"),
                    ("entregado", "Entregado"),
                    ("soltado", "Soltado en CD"),
                    ("descargado", "Descargado"),
                    ("vacio", "Vacío"),
                    ("vacio_en_ruta", "Vacío en Ruta"),
                    ("en_patio", "Vacío en Patio"),
                    ("devuelto", "Devuelto"),
                    ("cancelado", "Cancelado"),
                    ("incidente", "Incidente"),
                ],
                help_text="Último estado confirmado por fuente externa",
                max_length=20,
                null=True,
                verbose_name="Estado Verificado",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="retorno_destino_cd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retornos_vacios_recibidos",
                to="cds.cd",
                verbose_name="Patio destino retorno",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="retorno_destino_tipo",
            field=models.CharField(
                blank=True,
                choices=[("deposito", "Depósito naviera"), ("patio", "Patio")],
                max_length=12,
                null=True,
                verbose_name="Tipo destino retorno",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("automatico", "Automático (Puerto)"),
                    ("retiro_patio", "Retiro a Patio"),
                    ("retiro_directo", "Retiro Directo a Cliente"),
                ],
                default="automatico",
                max_length=20,
                verbose_name="Tipo de Movimiento",
            ),
        ),
    ]
