# Generated by Django 5.1.4 on 2025-10-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                ("comuna", models.CharField(max_length=100, verbose_name="Comuna")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("cliente", "Cliente"), ("ccti", "CCTI")],
                        default="cliente",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitud"
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitud"
                    ),
                ),
                (
                    "capacidad_vacios",
                    models.IntegerField(default=0, verbose_name="Capacidad Vacíos"),
                ),
                (
                    "vacios_actuales",
                    models.IntegerField(default=0, verbose_name="Vacíos Actuales"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Centro de Distribución",
                "verbose_name_plural": "Centros de Distribución",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["tipo", "activo"], name="cds_cd_tipo_f3acd6_idx"
                    ),
                    models.Index(fields=["codigo"], name="cds_cd_codigo_149620_idx"),
                ],
            },
        ),
    ]
