# Generated by Django 5.1.4 on 2025-10-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cd",
            name="permite_soltar_contenedor",
            field=models.BooleanField(
                default=False,
                help_text="Si True: conductor puede soltar contenedor y quedar libre inmediatamente (solo El Peñón)",
                verbose_name="Permite Drop & Hook",
            ),
        ),
        migrations.AddField(
            model_name="cd",
            name="requiere_espera_carga",
            field=models.BooleanField(
                default=False,
                help_text="Si True: conductor espera descarga sobre camión (Puerto Madero, Campos, Quilicura). Si False: drop & hook (El Peñón)",
                verbose_name="Requiere Espera para Carga",
            ),
        ),
        migrations.AddField(
            model_name="cd",
            name="tiempo_promedio_descarga_min",
            field=models.IntegerField(
                default=60,
                help_text="Tiempo estimado que toma descargar el contenedor en este CD",
                verbose_name="Tiempo Promedio Descarga (minutos)",
            ),
        ),
    ]
