# Generated by Django 5.1.4 on 2026-07-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0002_cd_permite_soltar_contenedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='geocerca_radio_m',
            field=models.PositiveIntegerField(blank=True, help_text='Si se configura, una posición dentro de este radio registra el arribo automáticamente.', null=True, verbose_name='Radio geocerca (metros)'),
        ),
    ]
