# Generated by Django 5.1.4 on 2026-10-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0003_cd_geocerca_radio_m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cd",
            name="permite_soltar_contenedor",
            field=models.BooleanField(
                default=False,
                help_text="Si True: conductor puede soltar contenedor y quedar libre inmediatamente",
                verbose_name="Permite Drop & Hook",
            ),
        ),
        migrations.AlterField(
            model_name="cd",
            name="requiere_espera_carga",
            field=models.BooleanField(
                default=False,
                help_text="Si True: conductor espera descarga sobre camión. Si False: drop & hook (contenedor soltado)",
                verbose_name="Requiere Espera para Carga",
            ),
        ),
        migrations.AlterField(
            model_name="cd",
            name="tipo",
            field=models.CharField(
                choices=[("cliente", "Cliente"), ("patio", "Patio")],
                default="cliente",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
