# Generated by Django 5.1.4 on 2026-07-19 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0003_cd_geocerca_radio_m'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='cliente_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_distribucion', to='clientes.clienteempresa', verbose_name='Empresa cliente'),
        ),
    ]
