name: Build Android APK

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build Debug APK
      run: cd android && ./gradlew assembleDebug --no-daemon

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: android/app/build/outputs/apk/debug/app-debug.apk
        body: |
          ## 📱 SoptraLoc Driver APK
          
          ### Instalación
          1. Descargar el APK en tu celular Android
          2. Si aparece "Origen desconocido", ir a:
             - Configuración → Seguridad → Permitir instalación desde orígenes desconocidos
          3. Instalar el APK
          4. Abrir la app
          5. Conceder permisos de ubicación → "Permitir todo el tiempo"
          
          ### Características
          - ✅ GPS continuo en background
          - ✅ Notificación persistente
          - ✅ Funciona con pantalla bloqueada
          - ✅ Bajo consumo de batería
          
          ### Requisitos
          - Android 6.0 (API 23) o superior
          - Conexión a internet
          - GPS activado
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
