name: Build Android APK

on:
  push:
    branches: [ main, master ]
    paths:
      - 'mobile-app/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'mobile-app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile-app/package-lock.json

    - name: Install dependencies
      working-directory: mobile-app
      run: npm ci

    - name: Make gradlew executable
      working-directory: mobile-app/android
      run: chmod +x gradlew

    - name: Build Debug APK
      working-directory: mobile-app/android
      run: ./gradlew assembleDebug --no-daemon

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: mobile-app/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Build Release APK
      working-directory: mobile-app/android
      run: ./gradlew assembleRelease --no-daemon
      continue-on-error: true

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: app-release
        path: mobile-app/android/app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 30
