# Generated by Django 5.1.4 on 2025-10-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0005_add_excel_fields'),
        ('drivers', '0001_initial'),
        ('programaciones', '0002_tiempooperacion_tiempoviaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Usuario')),
                ('canal', models.CharField(choices=[('sistema', 'Sistema/Dashboard'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20, verbose_name='Canal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipos_notificacion', models.JSONField(blank=True, default=list, verbose_name='Tipos de Notificación')),
                ('email_destino', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Destino')),
                ('telefono_destino', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Destino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
                'unique_together': {('usuario', 'canal')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ruta_iniciada', 'Ruta Iniciada'), ('eta_actualizado', 'ETA Actualizado'), ('arribo_proximo', 'Arribo Próximo'), ('llegada', 'Llegada Confirmada'), ('demurrage_alerta', 'Alerta Demurrage'), ('asignacion', 'Asignación de Conductor')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('archivada', 'Archivada')], db_index=True, default='pendiente', max_length=15, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('eta_minutos', models.IntegerField(blank=True, null=True, verbose_name='ETA (minutos)')),
                ('eta_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='ETA Timestamp')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distancia (km)')),
                ('lat_actual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud Actual')),
                ('lng_actual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud Actual')),
                ('detalles', models.JSONField(blank=True, default=dict, verbose_name='Detalles')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creada')),
                ('enviada_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada')),
                ('leida_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='containers.container', verbose_name='Contenedor')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='drivers.driver', verbose_name='Conductor')),
                ('programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='programaciones.programacion', verbose_name='Programación')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo', 'estado', '-created_at'], name='notificatio_tipo_9c4ebf_idx'), models.Index(fields=['prioridad', 'estado'], name='notificatio_priorid_ea05c7_idx'), models.Index(fields=['container', '-created_at'], name='notificatio_contain_931f61_idx'), models.Index(fields=['driver', '-created_at'], name='notificatio_driver__96cda5_idx')],
            },
        ),
    ]
